version: 2

services:
  - type: web
    name: expense-api
    env: go
    plan: free
    rootDir: .
    buildCommand: go build -o server ./cmd/api # build binary from root
    startCommand: ./server # run it
    port: 8080
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString

databases:
  - name: expense-db
    plan: free
    type: postgres
