version: 2

services:
  - type: web
    name: expense-api
    env: go
    plan: free
    rootDir: .
    buildCommand: go build -v -o server ./cmd/api && ls -la server
    startCommand: ./server
    port: 8080
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString

databases:
  - name: expense-db
    plan: free
    type: postgres
