version: 2

services:
  - type: web
    name: expense-api
    env: go
    plan: free
    rootDir: cmd/api # go into cmd/api/
    buildCommand: go build -o server . # build binary inside cmd/api/
    startCommand: ./server # run it
    port: 8080
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString

databases:
  - name: expense-db
    plan: free
    type: postgres
