services:
  - type: web
    name: expense-api
    env: go
    plan: free
    rootDir: cmd/api
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString

databases:
  - name: expense-db
    plan: free
    type: postgres
